### ISSUE TITLE
Update for 22.08

### ISSUE THREAD

**Issue by orowith2os** [flathub/org.freedesktop.Sdk.Extension.ldc#19]
Updating for 22.08 would be appreciated.

**Comment by hfiguiere** [comment]
branch created.

**Comment by gasinvein** [comment]
Wait, did it just built on 22.08? I'm pretty sure it didn't work before, that's why I still didn't update the SDK.

**Comment by hfiguiere** [comment]
better than the automatic dmd updates.

**Comment by gasinvein** [comment]
Well, anyway, let's ask @flathub/reviewers to change the default branch to `branch/22.08` here if it builds successfully now.
